// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDtZE1ZlnRzLPj3aWkJfgBcMjjnO81YtM',
    appId: '1:486331959690:web:b83c371c64d3acd495a073',
    messagingSenderId: '486331959690',
    projectId: 'geolocation-4f5fe',
    authDomain: 'geolocation-4f5fe.firebaseapp.com',
    storageBucket: 'geolocation-4f5fe.firebasestorage.app',
    measurementId: 'G-8P575PG8G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsTdae3D6sQQSaBcs-_5iXhcHqp15GjrU',
    appId: '1:486331959690:android:f2a3371683d030cf95a073',
    messagingSenderId: '486331959690',
    projectId: 'geolocation-4f5fe',
    storageBucket: 'geolocation-4f5fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2jETrFUwHTkdDI-Ruykx_pjWvSbCaFik',
    appId: '1:486331959690:ios:732c2661e7053dba95a073',
    messagingSenderId: '486331959690',
    projectId: 'geolocation-4f5fe',
    storageBucket: 'geolocation-4f5fe.firebasestorage.app',
    iosBundleId: 'com.example.geolocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2jETrFUwHTkdDI-Ruykx_pjWvSbCaFik',
    appId: '1:486331959690:ios:732c2661e7053dba95a073',
    messagingSenderId: '486331959690',
    projectId: 'geolocation-4f5fe',
    storageBucket: 'geolocation-4f5fe.firebasestorage.app',
    iosBundleId: 'com.example.geolocation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDtZE1ZlnRzLPj3aWkJfgBcMjjnO81YtM',
    appId: '1:486331959690:web:cadac72c970509bb95a073',
    messagingSenderId: '486331959690',
    projectId: 'geolocation-4f5fe',
    authDomain: 'geolocation-4f5fe.firebaseapp.com',
    storageBucket: 'geolocation-4f5fe.firebasestorage.app',
    measurementId: 'G-P9F5XWGE95',
  );
}
